### ISSUE TITLE
Loading Speed (important)

### ISSUE THREAD

**Issue by ssswhite0707** [ssswhite0707/Chatify#8]
@smurf-Azrael  Please investigate scrapbook performance at a high level. We should probably optimize mainly for median latencies first, find lowest hanging fruit...

**Comment by smurf-Azrael** [comment]
I have done it, please check it.

**Comment by ssswhite0707** [comment]
@smurf-Azrael  To be clear - I will consider this issue resolved once we have measured performance here, and made clear determinations of what needs to be optimized. Whatever those determinations are, we should create new issues tracking each individually, and set reasonable perf benchmarks that we believe we are achievable for each...

**Comment by smurf-Azrael** [comment]
hope to check together in server and estimate optimization status
